name: Cypress Tests

on:
  push:
    paths:
      - "cypress/e2e/1-login/login-pom.cy.js"

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: test login using pom
        uses: cypress-io/github-action@v6.1.0
        with:
          browser: chrome
          spec: cypress/e2e/1-login/login-pom.cy.js
